version: "2"

services:
  nginx:
    build: .docker/nginx
    volumes_from:
      - php
    volumes:
      - ./.docker/cache/nginx/logs:/var/log/nginx
    links:
      - php
    ports:
      - 80:80

  php:
    build: .docker/php
    expose:
      - 9001
    ports:
      - 9000:9000
    volumes:
      - .docker/cache/composer:/var/www/.composer/cache
      - ./:/var/www/html
    links:
      - db

  db:
    build: .docker/db
    ports:
      - 3306:3306
    volumes:
      - ./.docker/cache/db:/var/lib/mysql
      - ./.docker/db/entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8080:80
